[package]
name = "ruststack-lambda"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ruststack-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
dashmap = { workspace = true }
parking_lot = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
base64 = { workspace = true }
form_urlencoded = { workspace = true }
