[package]
name = "ruststack-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "ruststack"
path = "src/main.rs"

[dependencies]
ruststack-core.workspace = true
ruststack-s3.workspace = true
ruststack-sqs.workspace = true
ruststack-sns.workspace = true
ruststack-eventbridge.workspace = true
ruststack-ssm.workspace = true
ruststack-secretsmanager.workspace = true
ruststack-sts.workspace = true
ruststack-dynamodb.workspace = true
ruststack-kms.workspace = true
ruststack-logs.workspace = true
ruststack-iam.workspace = true
tokio.workspace = true
axum.workspace = true
tower.workspace = true
tower-http.workspace = true
http.workspace = true
http-body-util.workspace = true
bytes.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
fastrand.workspace = true
uuid.workspace = true
form_urlencoded.workspace = true
reqwest.workspace = true
