[package]
name = "ruststack-ssm"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "High-performance Amazon SSM Parameter Store engine for RustStack"

[dependencies]
ruststack-core = { path = "../ruststack-core" }
tokio = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
dashmap = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "ssm_bench"
harness = false
