[package]
name = "ruststack-benchmarks"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "ruststack-benchmarks"
path = "src/main.rs"

[dependencies]
ruststack-core.workspace = true
ruststack-s3.workspace = true
ruststack-sqs.workspace = true
ruststack-sns.workspace = true
ruststack-eventbridge.workspace = true
ruststack-ssm.workspace = true
ruststack-secretsmanager.workspace = true
ruststack-sts.workspace = true
ruststack-dynamodb.workspace = true
ruststack-kms.workspace = true
ruststack-logs.workspace = true
ruststack-iam.workspace = true
ruststack-cloudwatch.workspace = true
ruststack-ses.workspace = true
ruststack-kinesis.workspace = true
ruststack-lambda.workspace = true
tokio = { workspace = true }
bytes = { workspace = true }
base64 = { workspace = true }
serde = { workspace = true }
serde_json.workspace = true
clap.workspace = true
chrono.workspace = true
anyhow.workspace = true
