[package]
name = "ruststack-opensearch"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ruststack-core.workspace = true
tokio.workspace = true
axum.workspace = true
bytes.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
uuid.workspace = true
thiserror.workspace = true
dashmap.workspace = true
tracing.workspace = true
http-body-util.workspace = true
