[package]
name = "ruststack-cloudformation"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Fast in-memory AWS CloudFormation stack deployment and resource engine for RustStack"

[dependencies]
ruststack-core = { workspace = true }
ruststack-s3 = { path = "../ruststack-s3" }
ruststack-sqs = { path = "../ruststack-sqs" }
ruststack-sns = { path = "../ruststack-sns" }
ruststack-dynamodb = { path = "../ruststack-dynamodb" }
ruststack-iam = { path = "../ruststack-iam" }
tokio = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
quick-xml = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
dashmap = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
fastrand = { workspace = true }
form_urlencoded = { workspace = true }
serde_yaml = "0.9"

[dev-dependencies]
criterion = { workspace = true }
