[package]
name = "ruststack-s3"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ruststack-core.workspace = true
tokio.workspace = true
axum.workspace = true
http.workspace = true
http-body-util.workspace = true
bytes.workspace = true
serde.workspace = true
serde_json.workspace = true
quick-xml.workspace = true
chrono.workspace = true
uuid.workspace = true
dashmap.workspace = true
parking_lot.workspace = true
md-5.workspace = true
hex.workspace = true
base64.workspace = true
tracing.workspace = true
thiserror.workspace = true
form_urlencoded.workspace = true
regex.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "s3_bench"
harness = false
