[package]
name = "ruststack-cognito"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "High-performance Amazon Cognito IDP & User Pools engine for RustStack"

[dependencies]
ruststack-core = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
dashmap = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
base64 = { workspace = true }
sha2 = { workspace = true }
fastrand = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
reqwest = { workspace = true }
